# app/services/invoice_generator.py
from fpdf import FPDF
from datetime import datetime
from app.db import supabase
import logging

logger = logging.getLogger("agentshield.invoice")

class InvoicePDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 12)
        self.cell(0, 10, 'AgentShield OS | Internal Chargeback Invoice', align='R', new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Confidential Internal Document - Generated by AgentShield OS', align='C')

class InvoiceService:
    async def generate_monthly_invoice(self, tenant_id: str, cost_center_id: str, month: int, year: int) -> bytes:
        """
        Genera el artefacto financiero PDF agregando fuentes de datos financieros, ESG y seguridad.
        """
        
        # Rango de fechas
        start_date = f"{year}-{month:02d}-01"
        if month == 12:
            end_date = f"{year+1}-01-01"
        else:
            end_date = f"{year}-{month+1:02d}-01"

        # 1. AGREGACIÓN FINANCIERA (COMPUTE)
        try:
            receipts_res = supabase.table("receipts")\
                .select("cost_real, cost_gross, savings_usd")\
                .eq("tenant_id", tenant_id)\
                .eq("cost_center_id", cost_center_id)\
                .gte("created_at", start_date).lt("created_at", end_date)\
                .execute()
        except:
            receipts_res = type('obj', (object,), {'data': []})

        gross_spend = sum(r.get('cost_gross', 0) for r in receipts_res.data)
        actual_spend = sum(r.get('cost_real', 0) for r in receipts_res.data)
        arbitrage_savings = sum(r.get('savings_usd', 0) for r in receipts_res.data)

        # 2. AGREGACIÓN DE INGRESOS (KNOWLEDGE REVENUE) - Placeholder
        knowledge_revenue = 0.0 
        
        # 3. NET PAYABLE
        net_payable = actual_spend - knowledge_revenue

        # 4. CARBONO
        try:
            carbon_res = supabase.table("carbon_ledger")\
                .select("grams_co2, co2_avoided")\
                .eq("tenant_id", tenant_id)\
                .gte("created_at", start_date).lt("created_at", end_date)\
                .execute()
        except:
            carbon_res = type('obj', (object,), {'data': []})
            
        co2_total = sum(r.get('grams_co2', 0) for r in carbon_res.data)
        co2_saved = sum(r.get('co2_avoided', 0) for r in carbon_res.data)

        # =========================================================
        # GENERACIÓN PDF (FPDF2 Syntax)
        # =========================================================
        pdf = InvoicePDF()
        pdf.add_page()
        
        # Título
        pdf.set_font("Helvetica", "B", 20)
        pdf.cell(0, 15, f"INVOICE #{year}{month:02d}-{cost_center_id[:4].upper()}", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Billing Period: {month}/{year}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 6, f"Cost Center: {cost_center_id}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(10)

        # BLOQUE PRINCIPAL: FINANCIALS
        self._draw_kpi_box(pdf, "Net Payable", f"${net_payable:,.2f}", 0, 150, 0)
        pdf.ln(5)
        
        # Tabla Detallada
        pdf.set_font("Courier", "B", 10)
        pdf.cell(100, 8, "Description", border=1)
        pdf.cell(40, 8, "Amount (USD)", border=1, align="R")
        pdf.ln()
        
        pdf.set_font("Courier", "", 10)
        self._add_row(pdf, "Gross AI Consumption (Market Price)", gross_spend)
        self._add_row(pdf, "AgentShield Arbitrage Savings", -arbitrage_savings)
        self._add_row(pdf, "Knowledge Royalties (Income)", -knowledge_revenue)
        self._add_row(pdf, "Platform Fee (Standard)", 0.00)
        
        pdf.set_font("Courier", "B", 10)
        self._add_row(pdf, "TOTAL NET PAYABLE", net_payable)
        pdf.ln(10)

        # BLOQUE ESG & IMPACT
        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "ESG & Performance Impact", new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, 
            f"By using AgentShield Green Routing, your department avoided {co2_saved/1000:.2f} kg of CO2 emissions "
            f"compared to standard execution. Total footprint: {co2_total/1000:.2f} kg."
        )
        pdf.ln(5)
        pdf.cell(0, 6, f"Transactions Processed: {len(receipts_res.data)}", new_x="LMARGIN", new_y="NEXT")

        # FORENSIC LINK
        pdf.ln(10)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.multi_cell(0, 5, "This document is cryptographically verifiable. Audit specific transactions at: https://dashboard.agentshield.com/receipts")

        return pdf.output()

    def _add_row(self, pdf, label, value):
        pdf.cell(100, 8, label, border=1)
        pdf.cell(40, 8, f"${value:,.4f}", border=1, align="R")
        pdf.ln()

    def _draw_kpi_box(self, pdf, label, value, r, g, b):
        pdf.set_fill_color(240, 240, 240)
        pdf.rect(pdf.get_x(), pdf.get_y(), 190, 25, 'F')
        pdf.set_xy(pdf.get_x() + 5, pdf.get_y() + 5)
        
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, label.upper(), new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("Helvetica", "B", 18)
        pdf.set_text_color(r, g, b)
        pdf.cell(0, 10, value)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(15)

invoice_service = InvoiceService()
