# agentshield_core/app/routers/analytics.py
from fastapi import APIRouter, Depends
from app.db import supabase
from app.routers.authorize import get_tenant_from_header # O usar JWT si es para frontend web
import os

router = APIRouter(tags=["Analytics & Sustainability"])

# Usamos get_tenant_from_header para simular acceso API, 
# pero idealmente sería get_tenant_from_jwt para el dashboard visual.
# Para este MVP, reusamos la dependencia existente.

@router.get("/v1/analytics/sustainability")
async def get_carbon_dashboard(tenant_id: str = Depends(get_tenant_from_header)):
    """
    Devuelve el Reporte de Impacto Ambiental para que la empresa 
    lo ponga en su memoria de RSC (Responsabilidad Social Corporativa).
    """
    # Sumarizamos desde recibos (que ahora deben guardar 'carbon_g' en metadata)
    # Nota: Supabase no soporta sumas profundas en JSONB facilmente con la libreria cliente,
    # asi que traemos los ultimos 1000 recibos o hacemos una RPC. 
    # Para MVP, traemos data bruta (cuidado en prod).
    
    current_region = os.getenv("SERVER_REGION", "eu")
    
    # RPC Call (O(1) y 100% Preciso)
    try:
        res = supabase.rpc("get_total_carbon", {"p_tenant_id": tenant_id}).execute()
        total_co2 = float(res.data) if res.data else 0.0
    except Exception:
        # Fallback a 0.0 si falla RPC o no existe data
        total_co2 = 0.0
    
    # Un árbol maduro absorbe ~21kg de CO2 al año (~57g al día)
    trees_equivalent = total_co2 / 57.0 
    
    return {
        "tenant_id": tenant_id,
        "total_co2_grams": round(total_co2, 2),
        "equivalent_trees_planted_daily": round(trees_equivalent, 4),
        "energy_mix_rating": "A+" if current_region == "eu" else "B",
        "region_audit": current_region,
        "message": "Certificate of Green AI Compute generated by AgentShield.",
        "certification_standard": "AgentShield GreenIT v1.0"
    }
